#!/usr/bin/env -S node --no-warnings

import path from "path";
import { fileURLToPath } from "url";

import data from "../data/input.json" assert { type: "json" };

main();

function main() {
  const interfaces = data
    .map(
      (val) => `interface SomeInterface${val.name} {
  discriminator: "${val.name}";
  type: ${val.type};
}`,
    )
    .join("\n\n");
  const union =
    data
      .reduce(
        (acc, val) => acc + `SomeInterface${val.name} | `,
        "export type SomeInterface = ",
      )
      .slice(0, -3) + ";\n";

  const result = [interfaces, union].join("\n\n");

  const filename = fileURLToPath(import.meta.url);
  const basename = path.basename(filename);
  console.log(`/* autogenerated by ${basename} */`);

  console.log(result);
}
